
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/
export const DemandLevel = {
  high: 'high',
  medium: 'medium',
  low: 'low'
} as const

export type DemandLevel = (typeof DemandLevel)[keyof typeof DemandLevel]


export const MarketOutlook = {
  positive: 'positive',
  negative: 'negative',
  neutral: 'neutral'
} as const

export type MarketOutlook = (typeof MarketOutlook)[keyof typeof MarketOutlook]
